spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        generate_statistics: false
        use_sql_comments: true
        format_sql: true
        #https://question-it.com/questions/11967366/kak-zaregistrirovat-nestandartnye-funktsii-sql-vruchnuju-v-prilozhenii-spring-boot
        metadata_builder_contributor: ru.grigoriev.graduationproject.util.DB.RegisterFunction
        enable_lazy_load_no_trans: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:voting
    username: sa
    password:
  h2:
    console:
      enabled: true
  sql:
    init:
      data-locations: classpath:db/initDB.sql,classpath:db/populateDB.sql

server:
  port: 8080
  servlet:
    context-path: /app
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  token:
    secret: jwtappdemo
    expired: 36000000
